# Traefik Services - Backend Application Targets

http:
  # Services define WHERE to send traffic (the actual backend servers)
  services:
    # Authentik (local on edge VM)
    authentik-svc:
      loadBalancer:
        servers:
          - url: "http://authentik-server:9000"

    # Observability VM (10.10.10.112)
    portainer:
      loadBalancer:
        servers:
          - url: "https://10.10.10.112:9443"
        serversTransport: insecureTransport

    grafana:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:3000"

    prometheus:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:9090"

    loki:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:3100"

    alloy:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:12345"

    # VM 4: Media Apps (10.10.10.113)
    sonarr:
      loadBalancer:
        servers:
          - url: "http://10.10.10.113:8989"

    radarr:
      loadBalancer:
        servers:
          - url: "http://10.10.10.113:7878"

    prowlarr:
      loadBalancer:
        servers:
          - url: "http://10.10.10.113:9696"

    jellyfin:
      loadBalancer:
        servers:
          - url: "http://10.10.10.113:8096"

    qbittorrent:
      loadBalancer:
        servers:
          - url: "http://10.10.10.113:8080"

    n8n:
      loadBalancer:
        servers:
          - url: "http://10.10.10.113:5678"

    paperless:
      loadBalancer:
        servers:
          - url: "http://10.10.10.113:8000"

    # VM 5: Coolify (10.10.10.114)
    coolify:
      loadBalancer:
        servers:
          - url: "http://10.10.10.114:8000"

    # VM 2: Database Host (10.10.10.111)
    minio-console:
      loadBalancer:
        servers:
          - url: "http://10.10.10.111:9001"

    minio-api:
      loadBalancer:
        servers:
          - url: "http://10.10.10.111:9000"

  # Transports - Connection Settings for Backend Servers
  serversTransports:
    # Skip TLS verification for self-signed certs (like Portainer)
    insecureTransport:
      insecureSkipVerify: true
