# Traefik Static Configuration

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and Dashboard
api:
  dashboard: true
  insecure: true

# Entry Points
entryPoints:
  web:
    address: ":80"
    # Redirect HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "onurx.com"
            sans:
              - "*.onurx.com"

# Certificate Resolvers
certificatesResolvers:
  cloudflare:
    acme:
      email: onur03@gmail.com
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
        delayBeforeCheck: 30

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: edge_net
    watch: true

  file:
    directory: /dynamic
    watch: true

# Logging
log:
  level: INFO
  filePath: /data/logs/traefik.log
  format: json

# Access Logs
accessLog:
  filePath: /data/logs/access.log
  format: json
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-599"

# Metrics (for Prometheus)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    entryPoint: metrics

# Ping endpoint for health checks
ping:
  entryPoint: web
